### PR TITLE
[type: feat] Support .net 5.0 and 6.0

### PR DESCRIPTION
**Pull request by stulzq**
- Update target frameworks: remove net461, add net6.0/6.0
- Resolve dependency

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `dotnet test`.

### CODE REVIEW

**Review by dengliming — DISMISSED** [review]

**Comment by dengliming** [comment]
Please resolve the conflicts.

**Comment by hgaol** [comment]
> Please resolve the conflicts.

Hi, @dengliming , I prefer this PR fixing all the comments before merging it. And there's still one not be resolved. Because this PR removed the build CI for .net5. If no reasonable reason, I'd prefer closing it instead of merging.

**Comment by stulzq** [comment]
> > Please resolve the conflicts.
> 
> Hi, @dengliming , I prefer this PR fixing all the comments before merging it. And there's still one not be resolved. Because this PR removed the build CI for .net5. If no reasonable reason, I'd prefer closing it instead of merging.

.net 6.0 project can not build on image 5.x

**Comment by hgaol** [comment]
> > > Please resolve the conflicts.
> > 
> > 
> > Hi, @dengliming , I prefer this PR fixing all the comments before merging it. And there's still one not be resolved. Because this PR removed the build CI for .net5. If no reasonable reason, I'd prefer closing it instead of merging.
> 
> .net 6.0 project can not build on image 5.x

this project are supporting .net 5 and 6. We should make sure the .net 5 build can be successful. After this change, only .net6 are support to run test. If that case, I prefer discard this change.

We should let our change to meet the requirements of CI, not changing CI to meet our code.

**Pull request closed without merging**
